services:
  app:
    build:
      context: .  # Ubicación del Dockerfile
      dockerfile: Dockerfile
    container_name: arima-api
    ports:
      - "8000:8000"  # Exponer el puerto 8000
    environment:
      MODEL_PATH: ${ARIMA_MODELS_BUCKET_S3}  # Variable de entorno para el modelo

